apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-data
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-data
  template:
    metadata:
      labels:
        role: nfs-server-data
    spec:
      containers:
        - name: nfs-server
          image: gcr.io/google_containers/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data
              name: dev-matt-nfs-data

      volumes:
        - name: dev-matt-nfs-data
          gcePersistentDisk:
            pdName: dev-matt-nfs-data
            fsType: ext4
