apiVersion: v1
kind: Service
metadata:
  name: beaconchain-explorer-external-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: beaconchain-explorer-0
  ports:
    - name: frontend-port
      port: 80
      targetPort: 3333
      protocol: TCP

  type: LoadBalancer
  loadBalancerIP:
