apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chain-nodes
  labels:
    app: multinet
    tier: chain-nodes
spec:
  replicas: 1
  serviceName: chain-node
  selector:
    matchLabels:
      tier: chain-nodes
  template:
    metadata:
      generateName: lukso-
      labels:
        tier: chain-nodes
    spec:
      containers:
        - name: node
          image: ubuntu
          resources:
            requests:
              memory: "1000M"
              cpu: "1"
          imagePullPolicy: IfNotPresent
          command: [ "bash", "-c" ]
          ports:
            - name: pandora-rpc
              containerPort: 8545
              protocol: TCP
            - name: pandora-ws
              containerPort: 8546
              protocol: TCP
            - name: pandora
              containerPort: 30303
              protocol: TCP
            - name: vanguard-monit
              containerPort: 8080
              protocol: TCP
            - name: vanguard-grpc
              containerPort: 4000
              protocol: TCP
            - name: vanguard-p2p
              containerPort: 13000
              protocol: TCP
            - name: orch-ws
              containerPort: 7878
              protocol: TCP
            - name: orch-rpc
              containerPort: 7879
              protocol: TCP
          args:
            - apt-get update && apt-get install -y curl sudo wget unzip;
              curl https://install.l15.lukso.network | bash;
              echo $(which lukso);
              lukso start;
              tail -f /root/.lukso/l15/logs/pandora/"$(ls -1 /root/.lukso/l15/logs/pandora/ |grep log| head -1)";
          terminationMessagePolicy: FallbackToLogsOnError
