apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-data
  labels:
    name: common-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    name: common-data-test2-pvc
    namespace: default
  mountOptions:
    - hard
  nfs:
    path: /
    server: nfs-server-data.default.svc.cluster.local