kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: common-data-pvc
  namespace: closed-testnet
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
