apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-data
  labels:
    name: common-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    name: common-data-pvc
  mountOptions:
    - hard
  nfs:
    path: /
    server: nfs-server-data.develop.svc.cluster.local
