kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: common-data-pvc-default
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
