kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: common-data-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 50Gi