kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: common-data-test2-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi