apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-data-dev3
  labels:
    name: common-data-dev3
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    name: common-data-pvc-dev3
    namespace: dev
  mountOptions:
    - hard
  nfs:
    path: /
    server: nfs-server-data.default.svc.cluster.local
