apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-data-default
  labels:
    name: common-data-default
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    name: common-data-pvc-default
    namespace: default
  mountOptions:
    - hard
  nfs:
    path: /
    server: nfs-server-data.default.svc.cluster.local
