kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: common-data-pvc-dev-matt
  namespace: dev-matt
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
