kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: common-data-pvc-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi