apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-data-staging
  labels:
    name: common-data-staging
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    name: common-data-pvc-staging
    namespace: staging
  mountOptions:
    - hard
  nfs:
    path: /
    server: nfs-server-data.default.svc.cluster.local