kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deposits-storage-test-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 50Gi