apiVersion: v1
kind: PersistentVolume
metadata:
  name: deposits-storage-dev5
  labels:
    name: deposits-storage-dev5
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    name: deposits-storage-pvc-dev5
    namespace: dev
  mountOptions:
    - hard
  nfs:
    path: /
    server: nfs-server-deposit.dev.svc.cluster.local
