kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deposits-storage-pvc-default2
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi