apiVersion: v1
kind: PersistentVolume
metadata:
  name: deposits-storage
  labels:
    name: deposits-storage
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    name: deposits-storage-test2-pvc
    namespace: default
  mountOptions:
    - hard
  nfs:
    path: /
    server: nfs-server-deposit.default.svc.cluster.local