kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deposits-storage-test2-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi