kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deposits-storage-pvc-dev5
  namespace: dev
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
