kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deposits-storage-pvc-staging
  namespace: staging
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
