apiVersion: v1
kind: Service
metadata:
  name: eth2stats-grpc-external
spec:
  type: LoadBalancer
  selector:
    app: eth2stats-server
  ports:
    - protocol: TCP
      port: 9090
      name: grpc
  loadBalancerIP: 34.141.173.210
