apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: faucet-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: faucet-l15-external
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: multinet
spec:
  backend:
    serviceName: faucet-l15-external
    servicePort: 80
  tls:
    - hosts:
        - faucet.l15.lukso.network
      secretName: faucet-l15-lukso-network
  rules:
    - host: faucet.l15.lukso.network
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              serviceName: faucet-l15-external
              servicePort: 80
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              serviceName: faucet-l15-external
              servicePort: 80