apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: faucet-ingress
  annotations:
    {{- include "ingress-annotations" . | nindent 4 }}
  labels:
    app: multinet
spec:
  backend:
    serviceName: faucet-l15-external
    servicePort: 80
  tls:
    - hosts:
        - {{ include "env-prefix-host" . }}faucet.l15.lukso.network
      secretName: {{ include "env-prefix-secret" . }}faucet-l15-lukso-network
  rules:
    - host: {{ include "env-prefix-host" . }}faucet.l15.lukso.network
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: faucet-l15-external
              servicePort: 80
