apiVersion: v1
kind: Service
metadata:
  name: faucet-l15-external
spec:
  selector:
    app: faucet
  ports:
    - name: frontend-port
      port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
