apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: grafana-vanguard-testnet
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: multinet
spec:
  backend:
    serviceName: grafana-external-0
    servicePort: 80
  tls:
    - hosts:
        - grafana.vanguard.l15.lukso.network
      secretName: grafana-vanguard-l15-lukso-network
  rules:
    - host: grafana.vanguard.l15.lukso.network
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              serviceName: grafana-external-0
              servicePort: 80
          - path: /public/*
            pathType: ImplementationSpecific
            backend:
              serviceName: grafana-external-0
              servicePort: 80
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              serviceName: grafana-external-0
              servicePort: 80
          - path: /login/*
            pathType: ImplementationSpecific
            backend:
              serviceName: grafana-external-0
              servicePort: 80
