apiVersion: v1
kind: Service
metadata:
  name: vanguard-bootnode-external-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: vanguardbootnode-0
  ports:
    - name: vanguard-bootnode-port-udp
      port: 4000
      targetPort: 4000
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 35.204.255.172
