name: upgrade-multinet
on: [ repository_dispatch ]
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: namespace/dev
      - name: configure access
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          NAMESPACE: dev
        run: |
          export KUBECONFIG &&
          mkdir ~/.kube &&
          echo $KUBECONFIG | base64 -di > ~/.kube/config &&

      - name: upgrade
        env:
          NAMESPACE: dev
        run: |
          chmod +x ./auto.sh &&
          helm history eth20 --namespace $NAMESPACE
