name: upgrade-multinet
on: [ repository_dispatch ]
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: namespace/dev

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
      - name: Configure access to cluster
        env:
          CLUSTER_NAME: eth20
          CLUSTER_ZONE: europe-west4-a
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          PROJECT_NAME: l15-testnet
        run: |
          export GCLOUD_KEY &&
          gcloud config set project "$PROJECT_NAME" &&
          echo "$GCLOUD_KEY" | base64 --decode > gcloud.json &&
          gcloud auth activate-service-account --key-file=./gcloud.json &&
          gcloud container clusters get-credentials "$CLUSTER_NAME" \
          --zone "$CLUSTER_ZONE" \
          --project "$PROJECT_NAME" &&
          helm upgrade -f multinet-cluster/values.yaml eth20 ./multinet-cluster/ --namespace dev --dry-run


#       - name: Upgrade cluster
#         env:
#           NAMESPACE: dev
#           REPOSITORY: ${{ github.event.client_payload.repository }}
#           REPOSITORY_TAG: ${{ github.event.client_payload.tag }}
#         run: |
#           export REPOSITORY;
#           export REPOSITORY_TAG;
#           export NAMESPACE;

#           echo $REPOSITORY;
#           echo $REPOSITORY_TAG;
#           chmod +x ./auto.sh &&
#           ./auto.sh &&
#           git add multinet-cluster/values.yaml          
          
#       - name: Commit & Push changes
#         uses: actions-js/push@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: namespace/dev
