name: upgrade-multinet
on: [ repository_dispatch ]
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: namespace/dev
      - name: configure access
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          NAMESPACE: dev
        run: |
          ls -la &&
          echo "configured"

      - name: upgrade
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          NAMESPACE: dev
        run: |
          echo "Works"
          chmod +x ./auto.sh
          helm history --namespace $NAMESPACE
